name: deploy-tickets

on:
  push:
    branches:
      - master
    paths:
      - 'tickets/**'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ticketing-dev    # Add your cluster name here.
  GKE_ZONE: us-central1-c   # Add your cluster zone here.
  DEPLOYMENT_NAME: tickets-depl # deployment file from Infra/k8s
  SERVICE_NAME: tickets #folder where service is deployed (docker file)
  #IMAGE: static-site #e.g auth, client, orders
  #IMAGE_TAG: ${{ github.sha }} #use image tag instead of latest tag

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
   
    - name: "Build and push Docker image to Google Container Registry without action"
      run: |-
        gcloud auth configure-docker
        cd ${{ env.SERVICE_NAME }}
        docker build -t us.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest .
        docker push us.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl rollout restart deployment ${{ env.DEPLOYMENT_NAME }}
